### PR TITLE
feat: lint blocking calls

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by sigmaSd** [comment]
Not sure what you think about this but I add this lint a while back and the idea come from dax.

It caught mostly tests which is not that important, but it caught one usage inside cat command, fixing this lint would allow to programmatically stop introducing such things in the codebase again.

**Comment by sigmaSd** [comment]
Btw on another note I just noticed that the lint name is not in harmony with the others.

seems like it should be `sync-fn-inside-async-fn` like the other rule that describe the issue not the solution.

**Review by dsherret — APPROVED** [review]
Doesn't really matter for the tests, but this is good for the library itself. Thanks!

**Comment by sigmaSd** [comment]
Thanks @dsherret maybe if you have time , you can checkout https://github.com/denoland/deno_lint/pull/1199 do you think that the idea there is correct ?

**Pull request merged**
